### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by bookercodes**
_This pull request is **not** ready to be merged. I am opening it early to start a discussion._

### CODE REVIEW

**Comment by bookercodes** [comment]
@kosamari, 

I have encountered a small problem:

Now that the reports are sent in pages, it is no longer possible to auto-complete _all_ event name and location.

**Comment by bookercodes** [comment]
In my mind, there are two possible solutions to this problem:

#### Solution 1

Create a route: `/autoCompleteData` that returns all event locations and event names:

```
{
   "eventNames": ["foo conf", "bar conf"],
   "eventLocations": ["London"]
}
```

This benefit of this approach is that it will enable us to continue paginating reports on the server, which is good for performance.

The drawback of this approach is that it is more complicated than the current code.

### Solution 2

Remove server-side pagination and paginate on the client only. 

The benefit of this approach is that it keeps the code simple.

The drawback is that performance will suffer, especially as the database grows.

I am in favour of solution 1. What do you think?

**Comment by kosamari** [comment]
+1 for solution 1 :) 
Thank you for putting thoughts into this !

**Comment by bookercodes** [comment]
Ok, I think I'm done :smile:

**Comment by bookercodes** [comment]
I'll leave it up to you to tweak the UI e.g. the button reads _"load all"_ when it should read _"load more"_ or something. You'll probably want to show more than one report per page, too :exclamation:

**Comment by bookercodes** [comment]
Hi, @kosamari. Is there anything more I can do for this pull request?

**Comment by bookercodes** [comment]
Ping @kosamari

**Comment by bookercodes** [comment]
Do you think you'll have time to look at this this week, @kosamari ? Thanks.

**Comment by kosamari** [comment]
oops sorry hit wrong button

**Pull request merged**
